image: cirrusci/flutter:dev

stages:
  - build
  - analyze
  - test

before_script:
  - flutter pub get
  - flutter clean

build_linux:
  stage: build

  script:
    - flutter config --enable-linux-desktop
    - flutter build linux --release

  tags:
    - shared

build_android:
  stage: build

  script:
    - flutter build apk --release

  tags:
    - shared

build_web:
  stage: build

  script:
    - flutter config --enable-web
    - flutter build web --release
  
  tags:
    - shared

analyze:
  stage: analyze

  script:
    - flutter analyze

unit_test:
  stage: test

  script:
    - flutter test test/*
