image: cirrusci/flutter:dev

stages:
  - analyze
  - build
  - test

build_linux:
  stage: build
  before_script: [sudo apt update && sudo apt install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev -y]
  script:
    - flutter config --enable-linux-desktop
    - flutter clean
    - flutter pub get
    - flutter build linux --release
  artifacts:
    when: on_success
    paths:
      - build/linux/release/bundle/


  tags:
    - build
    - desktop
    - linux

build_android:
  stage: build

  script:
    - flutter clean
    - flutter pub get
    - flutter build apk --release

  tags:
    - build
    - android

build_web:
  stage: build

  script:
    - flutter config --enable-web
    - flutter clean
    - flutter pub get
    - flutter build web --release
  
  tags:
    - build
    - web

analyze:
  stage: analyze

  script:
    - flutter analyze
    - flutter format lib/ test/ --set-exit-if-changed

unit_test:
  stage: test

  script:
    - flutter test test/*
