image: cirrusci/flutter:dev

stages:
  - build
  - analyze
  - test

before_script:
  - flutter pub get
  - flutter clean

build:
  stage: build

  script:
    - flutter build linux

  tags:
    - shared


unit_test:
  stage: test

  script:
    - flutter test test/*

  tags:
    - shared

  stage: analyze

  script:
    - echo job excluded

  tags:
  - shared
