name: minestrix
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.5+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Matrix
  matrix:
    git:
      url: https://gitlab.com/minestrix/famedlysdk.git
      ref: henri2h/index-events-by-event-type

  flutter_olm: ^1.1.2
  flutter_openssl_crypto: ^0.1.0

  # Database
  hive_flutter: ^1.1.0

  provider: ^6.0.1
  
  # navigator
  auto_route: ^4.0.1

  # web navigator for SSO
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.3

  flutter_typeahead: ^4.0.0
  
  
  # Post formating
  flutter_markdown:
  emoji_picker_flutter: ^1.0.7

  # images
  image_picker:
  file_picker_cross:
  path_provider: ^2.0.5
  native_imaging:
    git: https://gitlab.com/famedly/company/frontend/libraries/native_imaging.git


  # time formating
  timeago: ^3.0.2

  # storage
  encrypt: ^5.0.1

  localstorage: ^4.0.0+1
  flutter_secure_storage: ^5.0.2
  
  # cache 
  flutter_cache_manager: ^3.0.1
  cached_network_image: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  # Notifications
  #firebase_messaging: ^7.0.3
  #flutter_local_notifications: ^3.0.2
  
  # Flushbar
  another_flushbar: ^1.10.25

  #dialogs
  adaptive_dialog: ^1.2.0
  
  package_info_plus: ^1.0.0
  
  minestrix_chat:
    git:
      url: https://gitlab.com/minestrix/minestrix-chat.git
  collection: ^1.15.0-nullsafety.4
  f_logs: ^2.0.0
  desktop_notifications: ^0.6.3
  flutter_app_lock: ^2.0.0
  flutter_local_notifications: ^9.4.0
  unifiedpush: ^4.0.0
  connectivity_plus: ^2.3.0
  just_audio: ^0.9.20
  flutter_ringtone_player: ^3.2.0
  sentry: ^6.5.1
  desktop_lifecycle: ^0.1.0
  callkeep: ^0.3.2
  wakelock: ^0.6.1+2
  flutter_webrtc: ^0.8.5

      
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.2
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
      - assets/verification.png
      - assets/sas-emoji.json
  

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf