name: piaf
description: A privacy focused social media based on matrix

publish_to: "none"

version: 2.0.0+15

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Matrix
  matrix:
    git: https://github.com/famedly/matrix-dart-sdk
  matrix_homeserver_recommendations: ^0.3.0


  # Cryptography
  encrypt: ^5.0.1
  flutter_olm: ^1.3.2
  flutter_openssl_crypto: ^0.3.0

  # Storage and database
  sqflite_common_ffi: ^2.3.2+1
  sqflite_sqlcipher: ^2.2.1
  localstorage: ^4.0.0+1
  flutter_secure_storage: ^9.0.0

  provider: ^6.0.1

  # navigator
  auto_route: ^7.4.0

  # web navigator for SSO
  webview_flutter: ^4.0.1
  url_launcher: ^6.0.3
  desktop_webview_window: ^0.2.0

  # Post formating
  flutter_markdown:
  emoji_picker_flutter: ^2.0.0-dev.5

  # images
  image_picker:
  file_picker: ^6.1.1
  path_provider: ^2.0.5
  native_imaging:
    git: 
      url: https://github.com/famedly/dart_native_imaging.git
      ref: nico/update-dependencies

  # Intl
  intl: ^0.19.0
  timeago: ^3.0.2

  # Cache
  flutter_cache_manager: ^3.0.1
  cached_network_image: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  # Notifications
  flutter_local_notifications: ^17.0.0
  # unifiedpush: ^5.0.0
  desktop_notifications: ^0.6.3

  # Calls
  callkeep: ^0.3.2
  flutter_webrtc: ^0.9.2
  flutter_ringtone_player: ^4.0.0

  
  # Lists
  scrollview_observer: ^1.19.0

  # Media 
  camera: ^0.10.5+2
  chewie: ^1.7.4
  photo_manager: ^3.0.0-dev.4
  photo_manager_image_provider: ^2.1.0
  video_player: ^2.5.3
  video_compress: ^3.1.2
  just_audio: ^0.9.20
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4 
  # Select according to https://github.com/media-kit/media-kit/tree/main/video_player_media_kit
  media_kit_libs_android_video: any
  media_kit_libs_linux: any

  # Chat UI
  flutter_chat_bubble: ^2.0.2
  flutter_html: ^3.0.0-beta.2
  universal_html: ^2.2.4

  # UI
  adaptive_dialog: ^2.0.0
  future_loading_dialog: ^0.3.0
  flutter_typeahead: ^5.0.1
  another_flushbar: ^1.10.25
  auto_size_text: ^3.0.0
  swipe_to: ^1.0.5
  shimmer: ^3.0.0
  dynamic_color: ^1.6.6
  
  # Settings
  settings_ui: ^2.0.2
  package_info_plus: ^5.0.1
  permission_handler: ^11.1.0

# Override due to https://github.com/mogol/flutter_secure_storage/issues/616
  audio_session: any

  flutter_slidable: ^3.0.1
  wakelock_plus: ^1.1.4
  flutter_blurhash:
      # Waiting for: https://github.com/fluttercommunity/flutter_blurhash/pull/59
    git: https://github.com/MominRaza/flutter_blurhash.git

  multi_split_view: ^2.4.0
  pasteboard: ^0.2.0
  flutter_highlighter: ^0.1.1
  flutter_foreground_task: ^6.1.2
  share_plus: ^7.2.1
  flutter_html_table: ^3.0.0-beta.2
  linkify: ^5.0.0
  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^5.0.1
  desktop_lifecycle: ^0.1.0
  flutter_datetime_picker_plus: ^2.1.0

dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/mogol/flutter_secure_storage
      ref: develop
      path: flutter_secure_storage_linux

  flutter_math_fork:
  # FIXME: we need this fix https://github.com/simpleclub-extended/flutter_math_fork/pull/87
    git:
      url: https://github.com/The-Redhat/flutter_math_fork/
      ref: 3442b36a436880ce1c023e25c868d6f4004c4c24


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.1.2
  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/verification.png
    - assets/sas-emoji.json
    - assets/bg_paris.jpg
    - assets/login_background.jpg
    - assets/piaf.jpg


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

