name: minestrix
description: A privacy focused social media based on matrix

publish_to: "none"

version: 1.6.5+13

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Matrix
  matrix:
    git:
      url: https://github.com/MinesTRIX/matrix-dart-sdk.git
      ref: henri2h/index-events-by-event-type

  flutter_olm:
    path: ../../olm/flutter
  flutter_openssl_crypto:
    path: ../../flutter_openssl_crypto

  # Database
  hive_flutter: ^1.1.0

  provider: ^6.0.1

  # navigator
  auto_route: ^7.4.0

  # web navigator for SSO
  webview_flutter: ^4.0.1
  url_launcher: ^6.0.3

  flutter_typeahead: ^4.0.0

  # Post formating
  flutter_markdown:
  emoji_picker_flutter: ^1.6.3

  # images
  image_picker:
  file_picker: ^6.1.1
  path_provider: ^2.0.5
  native_imaging:
    path: ../../native_imaging

  # time formating
  timeago: ^3.0.2

  # storage
  encrypt: ^5.0.1

  localstorage: ^4.0.0+1
  flutter_secure_storage: ^9.0.0

  # cache
  flutter_cache_manager: ^3.0.1
  cached_network_image: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  # Notifications
  flutter_local_notifications: ^16.1.0
  unifiedpush: ^5.0.0
  desktop_notifications: ^0.6.3

  # Flushbar
  another_flushbar: ^1.10.25

  #dialogs
  adaptive_dialog: ^2.0.0

  package_info_plus: ^4.1.0

  minestrix_chat:
    path: ../lib
  
  infinite_list:
    git:
      url: https://gitlab.com/minestrix/infinite-list.git
      ref: henri2h/enhancements

  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^5.0.1
  just_audio: ^0.9.20
  flutter_ringtone_player: ^4.0.0
  desktop_lifecycle: ^0.1.0
  callkeep: ^0.3.2
  flutter_webrtc: ^0.9.2
  desktop_webview_window: ^0.2.0
  settings_ui: ^2.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  scroll_to_index: ^3.0.1
  video_player: ^2.5.3
  camera: ^0.10.5+2
  dynamic_color: ^1.6.6
  media_kit: ^1.1.7
  video_compress: ^3.1.2
  photo_manager_image_provider: ^2.1.0

# Override due to https://github.com/mogol/flutter_secure_storage/issues/616
dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/mogol/flutter_secure_storage
      ref: develop
      path: flutter_secure_storage_linux

  flutter_math_fork:
  # FIXME: we need this fix https://github.com/simpleclub-extended/flutter_math_fork/pull/87
    git:
      url: https://github.com/The-Redhat/flutter_math_fork/
      ref: 3442b36a436880ce1c023e25c868d6f4004c4c24


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.1.2
  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/verification.png
    - assets/sas-emoji.json
    - assets/icon_512.png
    - assets/bg_paris.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

